---
title: "Custom PCA Chapter"
author: "Stefan Boeing stefan.boeing@crick.ac.uk"
date: 'Compiled: `r format(Sys.Date(), "%B %d, %Y")`'
abstract: "The main purpose of this module is to give you a copy-and-paste option to create custom PCA for your project. In the first part you will be able do download all relevant data directly into your R-session. For this you need to be inside the Crick or VPN connected to the Crick. Once you have the data loaded into your R-session, you can copy and paste the code to generate PCA plots on various sample selections."

output: 
    html_document:
        code_folding: hide
        df_print: tibble
        toc: true
        toc_depth: 5
        toc_float: true
        css: ../Main_Analysis/src/style/style.css

always_allow_html: yes

---

```{css setup_css, echo=FALSE}


.table{
  width:auto;
  font-size: 10px;
}

```

```{r setup, include=FALSE, warning=FALSE, message=F, echo=F, results=F}
knitr::opts_chunk$set(
    tidy = TRUE,
    tidy.opts = list(width.cutoff = 120),
    message = FALSE,
    warning = FALSE
)

# module purge;source /camp/stp/babs/working/software/modulepath_new_software_tree_2018-08-13;module load pandoc/2.2.3.2-foss-2016b;ml R/4.0.3-foss-2020a

#if (!require("remotes")){
#  install.packages("remotes")
#}

#remotes::install_github("rstudio/renv")

if (!file.exists("renv.lock")){
    renv::init()
} else {
    renv::restore(prompt = FALSE)
}

urlString <- "biologic.crick.ac.uk"
```



```{r set_directories, eval=T, echo=F, results=F}
## Setup plot collection object
library(knitr)
library(ggplot2)
library(ggpubr)
library(DT)
library(biologicSeqTools2)

addCorCatsToLabDb <- FALSE
figureCount <- 1
chnkVec <- as.vector(NULL, mode = "character")

VersionPdfExt <- paste0(".V", gsub("-", "", Sys.Date()), ".pdf")

if (dir.exists("/Volumes/babs/working/boeings/")){
    hpc.mount <- "/Volumes/babs/working/boeings/"
} else if (dir.exists("Y:/working/boeings/")){
    hpc.mount <- "Y:/working/boeings/"
} else if (dir.exists("/camp/stp/babs/working/boeings/")){
    hpc.mount <- "/camp/stp/babs/working/boeings/"
} else {
    hpc.mount <- ""
}

if (!exists("figureCount")){
    figureCount <- 1
}



## Heatmap setup ##
## Select Heatmap samples ##
FN <- paste0(hpc.mount, "Projects/reference_data/pwd_folder/babs.txt")
dbTable <- read.delim(
  FN,
  header = F,
  sep = "\t",
  stringsAsFactors = F
)

db.pwd <- as.vector(dbTable[1,1])
#setwd(Obio@parameterList$localWorkDir)

# The active biologic data object is expected to be found in ../../../../data/biologic_active_object/
source("../Main_Analysis/load.biologic.robj.R")
#
# # ObioFN <- paste0("../",list.files("..")[grep(".bioLOGIC.Robj", list.files(".."))])
# #
# # load(ObioFN)
#
#
# Obio <- setMountingPoint(Obio)
# Obio <- setAnalysisPaths(Obio)
# Obio <- setCrickGenomeAndGeneNameTable(Obio)
# Obio <- createAnalysisFolders(
#     Obio
# )
# Obio <- setDataBaseParameters(Obio)


# if (is.null(Obio@parameterList[["reportFigDir"]])){
#     Obio@parameterList[["reportFigDir"]] <- paste0(Obio@parameterList$html_local, "report_figures/")
# }
#
#
#
# ## Create outputfolders ##
# if (!dir.exists(Obio@parameterList[["reportFigDir"]])){
#     dir.create(Obio@parameterList[["reportFigDir"]])
# }

reportFigDir <- paste0(hpc.mount, "../../../../report_figures/")

if (!dir.exists(reportFigDir)){
    dir.create(reportFigDir)
}

figureCount <- 1

## Order design file ##
# dfDesign <- Obio@dfDesign
# orderVec <- unique(dfDesign$dataseries)
# orderVec <- c("WtFemale", "HetFemale", "HomFemale", "WtMale", "HomMale")
# 
# dfDesign$dataseries <- factor(dfDesign$dataseries, levels = orderVec)
# dfDesign <- dfDesign[order(dfDesign$dataseries),]
# Obio@dfDesign <- data.frame(NULL)
# Obio@dfDesign <- dfDesign
# source("save.biologic.robj.R")

```


<!-- Optional set data access parameters for R-users ------------------------->
```{r child = '02-B.1.2.set.data.access.parameters.for.R.data.import.Rmd', eval=TRUE, tidy=FALSE}
```

## Custom PCA Plot Creation
You can use the provided code to generate the PCA plots.

```{r alignment_dat, echo=TRUE, eval=TRUE, warning=FALSE, message = F, results='hide', tidy=TRUE}


###############################################################################
## Prepare annotation                                                        ##
## Annotate highlight genes
dfAnno <- unique(dfMainData[,c(geneIDcolumn, alignmentGeneID)])

# dfAnnoHL <- dfAnno[dfAnno[,geneIDcolumn] %in% highlightGenes,]


## Done with annotation                                                      ##
###############################################################################


##############################################################################
## Create dds object                                                        ##

dfDesign <- import.db.table.from.db(
  dbname = db,
  dbtable = designTB,
  host = host,
  port = port,
  user = username,
  password = pass
)

# Subset df design
pcaSampleList <- list(
  "PCAset1" = unique(
    dfDesign[dfDesign$dataseries %in% c("WTCD452", "WTCD451"), "sample_id"]
  ), #  All in vitro samples only
  "PCAset2" = unique(
    dfDesign[dfDesign$dataseries %in% c("KOCD451", "KOCD452"), "sample_id"]
  ), #AKPTmain, AKPTorg and AKPT2Dorg
  "PCAset3" = unique(
    dfDesign[dfDesign$dataseries %in% c("WTCD451", "KOCD451"), "sample_id"]
  ), #AKPTNTCsgRNA, AKPTYap1KO, AKPTWwtr1KO and AKPTCtnnb1KO
  "PCAset4" = unique(
    dfDesign[dfDesign$dataseries %in% c("WTCD452", "KOCD452"), "sample_id"]
  )
)


library(DESeq2)
chnkVec <- as.vector(NULL, mode = "character")
plotList <- list()

for (d in 1:length(pcaSampleList)){
    dfDesign <- import.db.table.from.db(
      dbname = db,
      dbtable = designTB,
      host = host,
      port = port,
      user = username,
      password = pass
    )

    ## Subset ##
    dfDesign <- dfDesign[dfDesign$sample_id %in% pcaSampleList[[d]],]

    colData = unique(dfDesign[, c("sample_id", "sample_group")])
    rownames(colData) = as.vector(colData$sample_id)
    colData$sample_id <- NULL
    colnames(colData)[1] = "condition"
    colData$condition <- as.factor(colData$condition)

    # dfRSEM <- Obio@RSEMcountMatrix





    dds <- DESeq2::DESeqDataSetFromMatrix(
      countData = dfCount[,row.names(colData)],
      colData   = colData,
      design    = ~ condition
    )

    ##                                                                           ##
    ###############################################################################

    ###############################################################################
    ## PCA plot                                                                  ##



    if (length(unique(dfDesign$sample_id)) > 50) {
      rld <- DESeq2::varianceStabilizingTransformation(dds)
    } else {
      rld <- DESeq2::rlog(dds)
    }

    rv <- rowVars(assay(rld))

    ## Added variable genes table
    #pcaSelectionVec = NULL
    #if (is.null(pcaSelectionVec)){
    select <- order(rv, decreasing = TRUE)[seq_len(NtopGenes)]
    Ntop4pcaGeneSelection <- row.names(assay(rld)[select, ])
    pcaSelectionVec <- row.names(assay(rld)[select, ])


    #}

    ##############################################
    ## Calculate PCA ##
    pca = prcomp(t(assay(rld)[pcaSelectionVec, ]))

    df.design.pca <- unique(dfDesign[,c("sample_id", "sample_group")])
    df.pca = data.frame(pca$x)
    names(df.pca) <- gsub("[.]", "_", names(df.pca))

    df.pca[["sample_id"]] <- row.names(df.pca)

    df.pca <- merge(
      df.design.pca,
      df.pca,
      by.x = "sample_id",
      by.y = "sample_id"
    )

    dfPCA <- df.pca




    PCApercentVar <- pca$sdev^2/sum(pca$sdev^2)

    ## Add percent variation plot ##
    PercentVariation <- round(100*PCApercentVar,1)
    PCdimension <- paste0("PC", 1:length(PercentVariation))
    df <- data.frame(
      PercentVariation,
      PCdimension
    )
    df <- df[df$PercentVariation > 0,]

    # library(ggplot2)
    # obj@plotCollection[["PCAvariationPerDimensionO"]] <- ggplot(df, aes(PCdimension, PercentVariation)) + geom_col() + scale_x_discrete(limits=PCdimension) +  theme(
    #     axis.text.y   = element_text(size=8),
    #     axis.text.x   = element_text(size=8),
    #     axis.title.y  = element_text(size=8),
    #     axis.title.x  = element_text(size=8),
    #     axis.line = element_line(colour = "black"),
    #     panel.border = element_rect(colour = "black", fill=NA, size=1),
    #     plot.title = element_text(hjust = 0.5, size = 12)
    # )

    #pcaFN <- "pca.table.txt"
    #fn = paste("PCA_plot.sample.groups.normalized.counts.png", sep="")
    #png(fn, type="cairo")
    #dev.off()

    ## Adding gene annotations ##
    dfBase <- assay(rld)[pcaSelectionVec, ]

    dfBase <- data.frame(t(dfBase))
    pcaGenes = prcomp(scale(dfBase))




    ###############################################################################
    ## Add PCA plot                                                              ##
    if (!exists("project_id")){
        project_id <- gsub("_designTable", "", designTB)
    }


    if (!exists("VersionPdfExt")){
        VersionPdfExt <- paste0(".V", gsub("-", "", Sys.Date()), ".pdf")
    }

    if (!exists("labname")){
        labname <- "TBD"
    }

    if (!exists("reportFigDir") || is.null(reportFigDir)){
        reportFigDir <- ""
    }










    tag <- paste0("PCAvariationPerDimension_", names(pcaSampleList)[d])


    # if (exists("Obio")){
    #     pos <- grep("PCApercentVar", slotNames(Obio))
    #     if (!is.null(PCApercentVar)){
    #         PCApercentVar <- PCApercentVar
    #     }
    # } else {
    #     PCApercentVar <- NULL
    # }


    ## Use custom PCA colors if specified ##

    ## Just in case we still have dots instead of underscores
    names(dfPCA) <- gsub("\\.", "_", names(dfPCA))
    pcaSampleGroups <- unique(sort(dfPCA$sample_group))

    ## If sample.group colors are set use those, otherwise set default.
    pos <- grep("^sample.group_color$", names(dfDesign))

    if (length(pos) == 0){
        ## Create default ##
        sample.group <- unique(dfDesign$sample.group)
        sample.group_color <- sample.group
                #library(scales)
        sample.group_color = scales::hue_pal()(length(sample.group_color))
                #sample.group_color = c("#990000", "#009900")

        ## set sample group colors manually

        dfGroupColors <- unique(data.frame(sample.group, sample.group_color))
        dfDesign <- merge(dfDesign, dfGroupColors, by.x = "sample.group", "sample.group")

    }

    dfColor <- unique(
            dfDesign[,c("sample_group", "sample_group_color")]
    )

    if (nrow(dfColor) == length(pcaSampleGroups)){

        namedColors <- dfColor$sample_group_color
        names(namedColors) <- dfColor$sample_group

        plotList[[tag]] <- ggplot2::ggplot(
            data = dfPCA,
            ggplot2::aes(x=PC1, y=PC2, fill = sample_group)
        ) + ggplot2::geom_vline(xintercept = 0, color = "grey", size=0.5
        ) + ggplot2::geom_hline(yintercept = 0, color = "grey", size=0.5
        ) + ggplot2::geom_point(
            size=2,
            shape = 21
        ) + ggplot2::scale_fill_manual("Sample Groups", values = namedColors
        )
    } else {
        plotList[[tag]] <- ggplot2::ggplot(
            data = dfPCA,
            ggplot2::aes(x=PC1, y=PC2, fill = sample_group)
        ) + ggplot2::geom_vline(xintercept = 0, color = "grey", size=0.5
        ) + ggplot2::geom_hline(yintercept = 0, color = "grey", size=0.5
        ) + ggplot2::geom_point(
            size=2,
            shape = 21
        )
    }




    if (!is.null(PCApercentVar)){
        plotList[[tag]] <- plotList[[tag]] + ggplot2::labs(
            title = "PCA Plot",
            x = paste0("PC1 \n ",round(100* PCApercentVar[1]),"% variability explained"),
            y = paste0("PC2 \n ",round(100* PCApercentVar[2]),"% variability explained")
        )
    } else {
        plotList[[tag]] <- plotList[[tag]] + ggplot2::labs(
            title = "PCA Plot",
            x = paste0("PC1"),
            y = paste0("PC2")
        )
    }

    plotList[[tag]] <- plotList[[tag]] +  ggplot2::theme_bw() + ggplot2::theme(
            axis.text.y   = ggplot2::element_text(size=8),
            axis.text.x   = ggplot2::element_text(size=8),
            axis.title.y  = ggplot2::element_text(size=12),
            axis.title.x  = ggplot2::element_text(size=12),
            axis.line = ggplot2::element_line(colour = "black"),
            panel.border = ggplot2::element_rect(colour = "black", fill=NA, size=1),
            plot.title = ggplot2::element_text(hjust = 0.5, size = 12)
    )


    ###########################################################################
    ## Save plot to file                                                     ##
    FNbase <- paste0(tag, VersionPdfExt)

    if (exists("Obio")){
        FN <- paste0(Obio@parameterList$reportFigDir, FNbase)
    } else {
        FN <- paste0(reportFigDir, FNbase)
    }
    FNrel <- paste0("report_figures/", FNbase)
    FNrelT <- paste0("report_tables/", FNbase)

    pdf(FN)
        print(plotList[[tag]])
    dev.off()
    ##                                                                       ##
    ###########################################################################



    # link <- paste0('<a href="https://biologic.crick.ac.uk/',project_id,'/pca?x_axis=PC1&y_axis=PC2', '" target="_blank">here</a>')
    link <- ""

    figCap <- paste0(
        "**Figure ",
        figureCount,
        ":** Variation in the first two PCA Dimensions. Download a pdf of this figure [here](", FNrel, "). ",
        "Further PCA dimensions are available interacively ", link, ". "
    )

    figureCount <- figureCount + 1

    NewChnk <- paste0(
    paste0("### ", tag ," \n"),
                "\n```{r ",tag,", results='asis', echo=F, eval=TRUE, warning=FALSE, fig.cap='",figCap,"'}\n",
                "\n",
                "\n print(plotList[['",tag,"']])",
                "\n cat(  '\n')",
                "\n\n\n```\n"
    )

    chnkVec <- c(
        chnkVec,
        NewChnk
    )
}


## Done with PCA plot                                                        ##
###############################################################################


```

Now you have a list called plotList containing all the plots. To view these plots in Rstudio directly, you can do:
```{r, eval=FALSE, echo=TRUE, class.source = 'fold-show'}
## Listing all plots in the list
names(plotList)

## Displaying the first plot in the list
print(plotList[[1]])

## Writing all plots to a pdf file
FN <- "output.pdf"
pdf(FN)
    plotList[[i]]
dev.off()

```

## PCA Plot Collection {.tabset .tabset-fade .tabset-dropdown}
```{r knit_cor_plot_characterization_plot, echo=F, eval=TRUE, message = F, warning=FALSE, results="asis"}
cat(paste(knit(text = chnkVec, quiet = T), collapse = '\n'))
```

## Documentation
```{r documentation, eval=TRUE, echo=F, results=T, error=F}
#renv::snapshot(prompt=FALSE)

print(paste0("Projectfolder: ", getwd()))

if (exists("Obio")){
    print(paste0("Project ID: ", Obio@parameterList$project_id))
}

sessionInfo()
```
