<!-- Set Parameters Module -->
<!-- Set the chnkPrefix to make all chunks unique in the overall folder -->
```{r, echo=FALSE, eval=TRUE, warning=FALSE}
chnkPrefix <- "edit.RSEM.tpm."
VersionPdfExt <- VersionPdfExt <- paste0(".",chnkPrefix,"V", gsub("-", "", Sys.Date()), ".pdf")

```

## DESeq2 Analysis
### Create DESeq2 object
```{r, echo=TRUE, eval=TRUE, warning=FALSE, results="asis"}
###############################################################################
## Create and attach DDS object                                              ##

if (is.null( Obio@parameterList$parallelProcessing) || length(Obio@parameterList$parallelProcessing) == 0){
     Obio@parameterList$parallelProcessing <- FALSE
}

Obio <- biologicSeqTools2::createDdsObject(Obio)

## Done creating and attaching DDS objecs                                    ##
###############################################################################
```

### Variation and PCA
```{r, echo=TRUE, eval=TRUE, warning=FALSE, results="hide", message=FALSE}
###############################################################################
## Determine variation in the data set                                       ##

## This is a tempory fix until the PCA function has been fully equipped for
## batch correction
saveMode <- Obio@parameterList$batchMode
Obio@parameterList$batchMode <- FALSE

Obio <- biologicSeqTools2::addCoVar(
    obj = Obio,
    avgCountCutOffperSample = 1,
    selectionColName = "aboveCutOff",
    dfBaseData = Obio@DESeqNormReadCountsTable,
    rowNameID = Obio@parameterList$primaryAlignmentGeneID
    #options: "DEseq2RV" or "CoVar"
)

## Results are in slot Obio@dataTableList$dfRowVar ##

## Diagnostic plot ##
# library(ggplot2)
# countCutOff <- 0
# pCoVar <- ggplot(
#     data=Obio@dataTableList$dfRowVar[Obio@dataTableList$dfRowVar$avgCountsPerGenePerSample > countCutOff ,],
#     aes(
#         x=CoVar,
#         y=DEseq2RV
#     )) + geom_point(
#     )  + labs(title = "Variation" ,x = "CoVar", y = "DeSeq2Var"
#     ) +  theme(
#         axis.text.y   = element_text(size=8),
#         axis.text.x   = element_text(size=8),
#         axis.title.y  = element_text(size=8),
#         axis.title.x  = element_text(size=8),
#         axis.line = element_line(colour = "black"),
#         panel.border = element_rect(colour = "black", fill=NA, size=1),
#         plot.title = element_text(hjust = 0.5, size = 12)
#     )

## Done determine variation in the data set                                  ##
###############################################################################

###############################################################################
## Perform PCA, MV-analysis, and Clusterdendrogram                           ##

## Select elements for PCA explicityly ##
dfSel <- Obio@dataTableList$dfRowVar

## Remove low count values ##
dfSel <- dfSel[dfSel$avgCountsPerGenePerSample >= 1, ]

## Order by variation
dfSel <- dfSel[order(dfSel$DEseq2RV, decreasing = TRUE),]
# dfSel <- dfSel[order(dfSel$CoVar, decreasing = TRUE),]

rowSelVec <- as.vector(
    dfSel[1:Obio@parameterList$NtopGenes,Obio@parameterList$primaryAlignmentGeneID]
)

Obio@dataTableList[["Ntop4pcaGeneSelection"]] <- rowSelVec



Obio <- doPCA(
    obj = Obio,
    pcaDimensionsToInvestigate = c(1:5),
    Ntop4pca = Obio@parameterList$NtopGenes, #500,
    avgCountCutOffperSample = 0,
    pcaSelectionVec = rowSelVec
)

Obio@parameterList$batchMode <- saveMode
## Do linear fittings to available dimensions ##


# depdendent Variation mode: Variables can be dependent (individual fits)


if (length(unique(Obio@dfDesign$dataseries)) > 1){
    independentDesignColSector <- c(
        "dataseries"
    )
} else {
    independentDesignColSector <- as.vector(NULL, mode = "character")
}

if (length(Obio@dfDesign$sample.group) > 1){
    independentDesignColSector <- c(
        independentDesignColSector,
        "sample.group"
    )
}

if (length(Obio@dfDesign$replicate) > 1){
    independentDesignColSector <- c(
        independentDesignColSector,
        "replicate"
    )
}

pos <- grep("^f_", names(Obio@dfDesign))
if (length(pos) > 0){
  independentDesignColSector <- c(
    names(Obio@dfDesign)[grep("^f_", names(Obio@dfDesign))]
  )

} else if (length(unique(Obio@dfDesign$dataseries)) > 1){
    independentDesignColSector <- c(
      "dataseries"
    )
}


# indedendentVariation mode: Variables are required to be independent
## Do linear variable fittings to PCA ##
# variables need to be independent > culmulative fit #
Obio <- doLinearFittings(
    obj = Obio,
    designColSelector = independentDesignColSector,
    mode = "independentVariation", ## "independentVariation" or "dependentVariation"
    Ntop4pca = Obio@parameterList$NtopGenes,
    plotname = "P2_independentVariables"
)



## Do linear variable fittings to PCA ##

# individual fit
LRTvec <- names(Obio@dfDesign)[grep("f_", names(Obio@dfDesign))]
#LRTvec <- LRTvec[LRTvec != "LRT_replicate"]
#LRTvec <- "LRT_timepoint"

dependentDesignColSelector<- c(
    independentDesignColSector,
    LRTvec,
    names(Obio@dfDesign)[grep("comp_", names(Obio@dfDesign))],
    names(Obio@dfDesign)[grep("LRT_", names(Obio@dfDesign))]
)
Obio <- doLinearFittings(
    obj = Obio,
    designColSelector = dependentDesignColSelector,
    mode = "dependentVariation", ## "independentVariation" or "dependentVariation"
    Ntop4pca = Obio@parameterList$NtopGenes,
    plotname = "P2_dependentVariables"
)


## Create Plot dendrogram ##
# Obio <- createSampleDendrogram(
#     obj = Obio,
#     Ntop4pca = Obio@parameterList$NtopGenes,
#     plotname = "dendrogram10000"
# )

###############################################################################
## Do differential gene expression analysis                                  ##
#Obio@parameterList$batchMode <- F
## LRT tests for multiple sample groups ##

if (!is.null(Obio@projectDetailList$DEseq2_DGE_result_folder) && Obio@projectDetailList$DEseq2_DGE_result_folder != ""){
    mode = "load_DGE_from_file"
    Obio <- loadDESeq2outputFromFile(
        Obio,
        replace = TRUE
    )
} else {
    mode = "calculate_LRT"
 
    dfDGE <- Obio@dfModel
    dfDGE <- dfDGE[dfDGE$test == "LRT",]
  
    if (nrow(dfDGE) > 0){
        Obio <- biologicSeqTools2::LRTanalysis(
            obj = Obio,
            createNewResultTable = TRUE
        )
    }
}


############################################################
## Function load DGE results from file
loadDESeq2outputFromFile <- function(
    Obio,
    replace = TRUE
){
    DEseq2resultDir <- Obio@projectDetailList$DESeq2_result_folder
    allfiles <- paste0(DEseq2resultDir, "/", list.files(DEseq2resultDir))
    allfiles <- allfiles[grep(".txt", allfiles)]
    contrastNames <- gsub(paste0(DEseq2resultDir, "/"), "", allfiles)
    contrastNames <- gsub(".txt", "", contrastNames)





    ###############################################################################
    ## For this project only: Add ENSMUSG column                                 ##
    dfAnno <- Obio@dfGeneAnnotation
    dfAnno <- unique(
      Obio@dfGeneAnnotation[,c(Obio@parameterList$primaryAlignmentGeneID, Obio@parameterList$geneIDcolumn)]
    )
    
    ## Done adding ENSMUSG column                                                ##
    ###############################################################################
    for (i in 1:length(allfiles)){
      colName <- contrastNames[i]
      res <- read.delim(allfiles[i], header = T, sep="\t")
      
      ################################
      ## This project only 
      dfAdd <- unique(dfAnno[dfAnno[,Obio@parameterList$geneIDcolumn] %in% res$symbol,  ])
      res <- merge(
          res,
          dfAdd,
          by.x = "symbol",
          by.y = Obio@parameterList$geneIDcolumn
      )
      
      
      selVec <- c("X", "baseMean", "log2FoldChange", "lfcSE", "stat", "pvalue", "padj")
      if (!sum(selVec %in% names(res)) == length(selVec)){
          stop(paste0("Check DESeq2 input files. Mandantory columns: ", paste0(selVec, collapse = ", ")))
      }
      
      res <- unique(res[,selVec])
      names(res) <- gsub("^X$", Obio@parameterList$primaryAlignmentGeneID, names(res))
      
      res <- res[!(duplicated(res[,Obio@parameterList$primaryAlignmentGeneID])),]
      res[is.na(res)] <- 0
      ## Done 
      ################################
      
      
      row.names(res) <- res[,Obio@parameterList$primaryAlignmentGeneID]
      
      names(res) = paste(names(res), colName, sep="_")
      res[[Obio@parameterList$primaryAlignmentGeneID]] = rownames(res)
      
      
      names(res) = gsub("log2FoldChange", "logFC", names(res))
      names(res) = gsub(
        "logFC",
        paste("contrast_", i, "_logFC", sep=""),
        names(res)
      )
      
      names(res) = gsub(
        "padj",
        paste("contrast_", i, "_padj", sep=""),
        names(res)
      )
      
      names(res) = gsub(
        "stat",
        paste("contrast_", i, "_stat", sep=""),
        names(res)
      )
      
      res$baseMean <- log2(res$baseMean)
      names(res) = gsub(
        "baseMean",
        paste("contrast_", i, "_lg2BaseMean", sep=""),
        names(res)
      )
      
      #Remove all rows without a padj
      padj.col = grep("padj", names(res))[1]
      res[,padj.col][is.na(res[,padj.col])] = ""
      res = res[res[,padj.col] != "", ]
      res[,padj.col] <- as.numeric(res[,padj.col])
      
      ## Add log10p column ##
      padj  <- names(res)[grep("_padj_", names(res))]
      lg10p <- gsub("padj", "lg10p", padj)
      
      for (z in 1:length(padj)){
        preprocess <- as.numeric(res[,padj[z]])
        minNum <- min(preprocess[preprocess != 0])
        preprocess[preprocess == 0] <- minNum
        
        # if (length(grep("padj_LRT", padj[i])) > 0){
        #     preprocess <- as.numeric(res[,padj[z]])
        #     minNum <- min(preprocess[preprocess != 0])
        #     preprocess[preprocess == 0] <- minNum
        # } else {
        #     preprocess <- as.numeric(res[,padj[z]])
        # }
        
        temp <- -1*log10(preprocess)
        #temp[temp >= 50] = 50
        res[,lg10p[z]] <- temp
      }
      
      col.vector = c(
        Obio@parameterList$primaryAlignmentGeneID,
        names(res)[grep("contrast", names(res))]
      )
      
      res = res[,col.vector]
      
      ## Make all numeric columns numeric ##
      res[,grep("contrast_", names(res))] <- apply(res[,grep("contrast_", names(res))], 2, as.numeric)
      
      if (i == 1){
        dfContrastTable <- res
      } else {
        dfContrastTable <- merge(
          dfContrastTable,
          res,
          by.x = Obio@parameterList$primaryAlignmentGeneID,
          by.y = Obio@parameterList$primaryAlignmentGeneID,
          all = TRUE
        )
        dfContrastTable[is.na(dfContrastTable)] <- 0
      }
    }
    
    
    # head(dfContrastTable)
    
    dfContrastTable<- dfContrastTable[rowSums(dfContrastTable[,2:ncol(dfContrastTable)]) != 0, ]
    
    if (replace){
        Obio@DEseq2contrastTable <- data.frame(NULL)
    }
    
    Obio@DEseq2contrastTable <- dfContrastTable
    print("DESeq2 results loaded into Obio@DEseq2contrastTable")
    
    return(Obio)
}

## Done 
#############################################################

## If mode is not calculate DGE, a dge table needs to be provided
if (!is.null(Obio@projectDetailList$DEseq2_DGE_result_folder) && Obio@projectDetailList$DEseq2_DGE_result_folder != ""){
    mode = "load_DGE_from_file"
    Obio <- loadDESeq2outputFromFile(
        Obio,
        replace = TRUE
    )
} else {
    mode = "calculate_DGE"
    
    ## Pairwise differential gene expression ##
    ## If working on projects prior to fall 2018, make sure
    ## Obio@parameterList$DEseq2betaPrior is set to true.
    dfDGE <- Obio@dfModel
    dfDGE <- dfDGE[dfDGE$test == "Wald",]

    if (nrow(dfDGE) > 0){
        Obio <- biologicSeqTools2::DGEanalysis(
            obj = Obio,
            createNewResultTable = TRUE
        )
    }
}



## Done differential gene expresison analysis                                ##
###############################################################################

###############################################################################
## Prepare documentation                                                     ##

## To be added ##
## consider using spin on the written out scriptVec
#Obio <- createRMDscript(Obio)

## Done with documentation                                                   ##
###############################################################################

###############################################################################
## Add plots


## Done 
###############################################################################
```


