<!-- Set PArameters Module -->
<!-- Set the chnkPrefix to make all chunks unique in the overall folder -->
```{r partC_retrieve_reference_gene_sets_init, echo=TRUE, eval=TRUE, warning=FALSE}
chnkPrefix <- "C2.ref.gmt."
VersionPdfExt <- VersionPdfExt <- paste0(".",chnkPrefix,"V", gsub("-", "", Sys.Date()), ".pdf")

```


### Load Reference Gene Sets from database or gmt file
```{r partC_create_sample_list, echo=TRUE, eval=TRUE, warning=FALSE, results=F}
###############################################################################
## Load reference datasets                                                   ##


Obio@dataTableList[["referenceList"]] <- NULL

if (!is.null(Obio@dbDetailList$host)){
  
    if (Obio@parameterList$geneIDcolumn != "mgi_symbol" & Obio@parameterList$geneIDcolumn != "hgnc_symbol") {
    queryGS <- "hgnc_symbol" 
  } else {
            queryGS <- Obio@parameterList$geneIDcolumn
  }
  
    Obio@dataTableList[["referenceList"]] <- list(
        "TFs" = retrieve.gene.category.from.db(
                          cat_id = "ag_lab_categories__10",
                          password = db.pwd,
                          gene.symbol = queryGS,
                          user = Obio@dbDetailList$db.user,
                          host = Obio@dbDetailList$host
                    )
        
      )
}




## Done create cellRanger QC plots                                           ##
###############################################################################


```


